# Generated by Django 5.2.6 on 2025-09-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_issueprivatechat_issueprivatemessage_jobprivatechat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuemessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='issuemessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='jobchatroom',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='jobmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='IssueChatRoom',
        ),
        migrations.DeleteModel(
            name='IssueMessage',
        ),
        migrations.DeleteModel(
            name='JobChatRoom',
        ),
        migrations.DeleteModel(
            name='JobMessage',
        ),
    ]
